apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
    - default:
        cpu: 1
        memory: 750Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      type: Container