kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: default
  labels:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    deployment: prometheus
  type: LoadBalancer